import { v4 as uuidv4 } from 'uuid';
 export const Products = [
    {
   id  : uuidv4(),
   title : "Vivo V20 Pro 8 GB 128 GB Midnight Jazz",
   image : '/assets/images/Mobiles/vivo V20 pro.webp',
   price  : "₹29990",
   rating : "3.6",
   quantity : 1,
   updatedPrice : 29990,
   category : "Mobile",
    },

    {
     id  : uuidv4(),
     title : "Apple iPhone 12 Pro Max 256 Gb Graphite",
     image :'/assets/images/Mobiles/Apple iPhone 12 pro max.webp',
     price  : "₹139900",
     rating : "5",
     quantity : 1,
     updatedPrice : 139900,
     category : "Mobile",
    },

    {
       id  : uuidv4(),
       title : "Redmi 9 Power 4 GB 64 GB Blazing Blue",
       image : '/assets/images/Mobiles/Redmi 9 power.webp',
       price  : "₹11421",
       rating : "3.8",
       quantity : 1,
       updatedPrice : 11421,
       category : "Mobile",
      },

        {
         id  : uuidv4(),
         title : "OPPO A53 6 GB 128 GB Mint Cream",
         image : '/assets/images/Mobiles/oppo.webp',
         price  : "₹15490",
         rating : "5",
         quantity : 1,
         updatedPrice : 15490,
         category : "Mobile",
       },
       {
        id  : uuidv4(),
        title : "Samsung Galaxy A32 6 GB 128 GB Black",
        image : '/assets/images/Mobiles/samsung.webp',
        price  : "₹20499",
        rating : "5",
        quantity : 1,
        updatedPrice : 20499,
        category : "Mobile",
      },

      {
        id  : uuidv4(),
        title : "Nokia 5.4 6 GB 64 GB Polar Night",
        image : '/assets/images/Mobiles/Nokia.webp',
        price  : "₹16190",
        rating : "",
        quantity : 1,
        updatedPrice : 16190,
        category : "Mobile",
      },
     
      {
        id  : uuidv4(),
        title : "Philips BT3101/15 Beard Trimmer For Men ( White , Rechargeable Battery )",
        image : '/assets/images/Electronics/Trimmer.webp',
        price  : "₹1349",
        rating : "3.9",
        quantity : 1,
        updatedPrice : 1349,
        category : "Electronics",
      },

      {
        id  : uuidv4(),
        title : "Realme Selfie Tripod & Wireless Bluetooth 5.1 Remote (Black)",
        image : '/assets/images/Electronics/Tripod.webp',
        price  : "₹1299",
        rating : "5",
        quantity : 1,
        updatedPrice : 1299,
        category : "Electronics",
      },

      {
        id  : uuidv4(),
        title : "boAt Airdopes 131 True Wireless Bluetooth Headset ( Blue )",
        image : '/assets/images/Electronics/BoatAirdopes.webp',
        price  : "₹1299",
        rating : "4",
        quantity : 1,
        updatedPrice : 1299,
        category : "Electronics",
      },

      {
        id  : uuidv4(),
        title : "Sony Dual Shock4 Wireless Controller Gamepad For PS4 (Black)",
        image : '/assets/images/Electronics/Sony Gamepad.webp',
        price  : "₹5050",
        rating : "",
        quantity : 1,
        updatedPrice : 5050,
        category : "Electronics",
      },

      {
        id  : uuidv4(),
        title : "Syska HD1600 TRENDSETTER 1000 W Hair Dryer ( Teal )",
        image :'/assets/images/Electronics/Hair dryer.webp',
        price  : "₹780",
        rating : "4.1",
        quantity : 1,
        updatedPrice : 780,
        category : "Electronics",
      },

      {
        id  : uuidv4(),
        title : "SanDisk Ultra Dual Drive Go 32 GB Type C Pendrive for Mobile - SDDDC3-032G-I35",
        image : '/assets/images/Electronics/Sandisk.webp',
        price  : "₹729",
        rating : "3.9",
        quantity : 1,
        updatedPrice : 729,
        category : "Face Mask",
      },

      //facemask

      {
        id  : uuidv4(),
        title : "Venus V4400 Anti Pollution Activate N95 Niosh Certified Mask (Pack Of 4)",
        image : '/assets/images/Face Mask/venusmask.webp',
        price  : "₹195",
        rating : "4",
        quantity : 1,
        updatedPrice : 195,
        category : "FaceMask",
      },

      {
        id  : uuidv4(),
        title : "Lee Cooper Lightweight Multi-Layer Melange Face Mask Filter With Heiq Vblock For Outdoor Protection Super Breathable & Reusable Cloth (Pack Of 4)",
        image : '/assets/images/Face Mask/leecoopermask.webp',
        price  : "₹499",
        rating : "3.4",
        quantity : 1,
        updatedPrice : 499,
        category : "FaceMask",
      },

      {
        id  : uuidv4(),
        title : "Extra Bass Disposable Surgical 3 Ply Mask ( Pack of 100 )",
        image : '/assets/images/Face Mask/surgicalmask.webp',
        price  : "₹279",
        rating : "2.6",
        quantity : 1,
        updatedPrice : 279,
        category : "FaceMask",
      },

      {
        id  : uuidv4(),
        title : "jars Collections Set Of 5 Fashion Mask",
        image : '/assets/images/Face Mask/jarsmask.webp',
        price  : "₹199",
        rating : "2.1",
        quantity : 1,
        updatedPrice : 199,
        category : "FaceMask",
      },

      {
        id  : uuidv4(),
        title : "Wildcraft W95 HYPASHIELD Anti Pollution Activate 3 Layer Mask (Pack of 2)",
        image : '/assets/images/Face Mask/wildcraftmask.webp',
        price  : "₹174",
        rating : "",
        quantity : 1,
        updatedPrice : 174,
        category : "FaceMask",
      },

      {
        id  : uuidv4(),
        title : "Tara Care Non Valve Anti Pollution KN95 Mask (Pack of 3)",
        image : '/assets/images/Face Mask/taracaremask.webp',
        price  : "₹129",
        rating : "2.9",
        quantity : 1,
        updatedPrice : 129,
        category : "FaceMask",
      },


      //"Covid Essential"
      {
        id  : uuidv4(),
        title : "Himalaya 1L Orange Pure Hands Sanitizer with Alcohol - Set of 2 Bottles, 500ml each",
        image : '/assets/images/Covid Essential/himalayasani.webp',
        price  : "₹399",
        rating : "4.3",
        quantity : 1,
        updatedPrice : 399,
        category : "CovidEssential",
      },

      {
        id  : uuidv4(),
        title : "Aryanveda Bodyguard Hand Sanitizer 100 ml (Pack of 24)",
        image : '/assets/images/Covid Essential/aryanvedasani.webp',
        price  : "₹589",
        rating : "",
        quantity : 1,
        updatedPrice : 589,
        category : "CovidEssential",
      },

      {
        id  : uuidv4(),
        title : "Axiom Medicated Hand Sanitizer 5L",
        image : '/assets/images/Covid Essential/axiomsani.webp',
        price  : "₹699",
        rating : "2.9",
        quantity : 1,
        updatedPrice : 699,
        category : "CovidEssential",
      },

      {
        id  : uuidv4(),
        title : "Lifebuoy Germ Protection Total 10 Hand Wash 5 L (Pack of 2)",
        image : '/assets/images/Covid Essential/lifebuoysani.webp',
        price  : "₹1600",
        rating : "4.5",
        quantity : 1,
        updatedPrice : 1600,
        category : "CovidEssential",
      },

      {
        id  : uuidv4(),
        title : "Floh Disinfectant Hand Wash 5L,Rose Flavor",
        image : '/assets/images/Covid Essential/flohsani.webp',
        price  : "₹499",
        rating : "2.6",
        quantity : 1,
        updatedPrice : 499,
        category : "CovidEssential",
      },

      {
        id  : uuidv4(),
        title : "Patanjali Hand Sanitizer 120 ml ( Pack of 1 )",
        image : '/assets/images/Covid Essential/patanjalisani.webp',
        price  : "₹55",
        rating : "4.4",
        quantity : 1,
        updatedPrice : 55,
        category : "CovidEssential",
      },

      //Men's Fashion
      {
        id  : uuidv4(),
        title : "Bi Fashion Contrast Hood Full Designer Men's T-shirts",
        image : '/assets/images/MensFashion/bitshirt.webp',
        price  : "₹349",
        rating : "4",
        quantity : 1,
        updatedPrice : 349,
        category : "MensFashion",
      },
      {
        id  : uuidv4(),
        title : "Ample Men Multi Regular fit Cotton Blend Round neck T-Shirt - Pack Of 2",
        image : '/assets/images/MensFashion/ampletshirt.webp',
        price  : "₹449",
        rating : "3.7",
        quantity : 1,
        updatedPrice : 449,
        category : "MensFashion",
      },

      {
        id  : uuidv4(),
        title : "Castoes Men Running Shoes Running Shoes ( Black )",
        image : '/assets/images/MensFashion/castoes.webp',
        price  : "₹520",
        rating : "3.2",
        quantity : 1,
        updatedPrice : 520,
        category : "MensFashion",
      },

      {
        id  : uuidv4(),
        title : "T R Men 35-Black-6, Training/Gym Shoes ( Black )",
        image : '/assets/images/MensFashion/trshoes.webp',
        price  : "₹349",
        rating : "2.6",
        quantity : 1,
        updatedPrice : 349,
        category : "MensFashion",
      },

      {
        id  : uuidv4(),
        title : "Parx Men Beige Solid Slim fit Regular trousers",
        image : '/assets/images/MensFashion/parx.webp',
        price  : "₹989",
        rating : "5",
        quantity : 1,
        updatedPrice : 989,
        category : "MensFashion",
      },

      {
        id  : uuidv4(),
        title : "FASHLOOK Men Brown Leather Bi-Fold Wallet ( Pack of 1 )",
        image : '/assets/images/MensFashion/fashlook.webp',
        price  : "₹170",
        rating : "3.4",
        quantity : 1,
        updatedPrice : 170,
        category :"MensFashion",
      },


      //Women's Fashion" 

      {
        id  : uuidv4(),
        title : "Rangriti Women Blue Solid Straight Kurta",
        image : '/assets/images/WomensFashion/rangriti.webp',
        price  : "₹500",
        rating : "",
        quantity : 1,
        updatedPrice : 500,
        category :"WomensFashion",
      },
      {
        id  : uuidv4(),
        title : "DIVYANSHI FASHIONS Women Black Printed Regular Kurti With Sharara And Dupatta",
        image : '/assets/images/WomensFashion/divyanshi.webp',
        price  : "₹999",
        rating : "5",
        quantity : 1,
        updatedPrice : 999,
        category :"WomensFashion",
      },
      {
        id  : uuidv4(),
        title : "Moonwalk Women Pink One Toe Flats",
        image : '/assets/images/WomensFashion/moonwalk.webp',
        price  : "₹299",
        rating : "3.9",
        quantity : 1,
        updatedPrice : 299,
        category :"WomensFashion",
      },
      {
        id  : uuidv4(),
        title : "BIG BIRD FOOTWEAR Women Black Sandals",
        image : '/assets/images/WomensFashion/bigbird.webp',
        price  : "₹399",
        rating : "3.7",
        quantity : 1,
        updatedPrice : 399,
        category :"WomensFashion",
      },
      {
        id  : uuidv4(),
        title : "Sukkhi Elegant Gold Plated Maroon & Blue Meenakari Mangalsutra Set for Women",
        image : '/assets/images/WomensFashion/sukkhi.webp',
        price  : "₹299",
        rating : "",
        quantity : 1,
        updatedPrice : 299,
        category :"WomensFashion",
      },
      {
        id  : uuidv4(),
        title : "RG FASHIONS Pink Meenakari Stones Peacock Design Pendant Ball Chain Necklace Jewellery Set For Women",
        image : '/assets/images/WomensFashion/rg.webp',
        price  : "₹314",
        rating : "",
        quantity : 1,
        updatedPrice : 314,
        category :"WomensFashion",
      },
];


